backend:
  name: git-gateway
  branch: cms
media_folder: "tablepointer.com/content/images/uploads"
public_folder: "/images/uploads"
logo_url: tablepointer.com/src/assets/images/logo.webp
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "tablepointer.com/content/home.json"
        fields:
          - {label: Heading Text, name: headingText, widget: string}
          - {label: Button Text, name: buttonText, widget: string}