backend:
  name: git-gateway
  branch: cms
media_folder: "tablepointer.com/content/images/uploads"
public_folder: "/images/uploads"
logo_url: logo.webp
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "tablepointer.com/content/home.json"
        fields:
          - {label: Heading Text, name: headingText, widget: string}
          - {label: Button Text, name: buttonText, widget: string}
          - {label: Benefit One Title, name: benefitOneTitle, widget: string}
          - {label: Benefit One Text, name: benefitOneText, widget: string}
          - {label: Benefit Two Title, name: benefitTwoTitle, widget: string}
          - {label: Benefit Two Text, name: benefitTwoText, widget: string}
          - {label: Benefit Three Title, name: benefitThreeTitle, widget: string}
          - {label: Benefit Three Text, name: benefitThreeText, widget: string}
          - {label: Kitchen Section Title, name: kitchenSectionTitle, widget: string}
          - {label: Kitchen Section Paragraph One, name: kitchenSectionPOne, widget: string}
          - {label: Kitchen Section Paragraph Two, name: kitchenSectionPTwo, widget: string}