backend:
  name: git-gateway
  branch: cms
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "./content/home.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
          - label: Section One
            name: sectionOne
            widget: list
            fields:
              - {label: Heading Text, name: headingText, widget: string}
              - {label: Button Text, name: buttonText, widget: string}